eShop.AdminAplication/Controllers/Component/PagerViewComponent.cs
using eShop.ViewModels.Catalog.Common;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace eShop.AdminAplication.Controllers.Component
{
    public class PagerViewComponent :ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

eShop.AdminAplication/Controllers/ProductController.cs
using eShop.AdminAplication.Services;
using eShop.Application.Catalog.Products;
using eShop.Utilities.Constants;
using eShop.ViewModels.Catalog.Common;
using eShop.ViewModels.Catalog.Products;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Threading.Tasks;

namespace eShop.AdminAplication.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductApiClient _productApiClient;
        private readonly IConfiguration _configuration;
        private readonly ICategoryApiClient _categoryApiClient;

        public ProductController(IProductApiClient productApiClient, IConfiguration configuration, ICategoryApiClient categoryApiClient)
        {
            _categoryApiClient = categoryApiClient;
            _productApiClient = productApiClient;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index(int pageIndex = 1, int? cateId = null, int pageSize = 10, string keyword = null)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLangId);

            var request = new GetManageProductPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                PageSize = pageSize,
                LanguageId = languageId,
                CategoryId = cateId,
            };

            var category = await _categoryApiClient.GetAll(languageId);
            ViewBag.Categories = category.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = cateId.HasValue && cateId.Value.ToString() == x.Id.ToString()
            });

            var data = await _productApiClient.GetProductPaging(request);
            ViewBag.keyword = keyword;

            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }

            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }


        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create([FromForm] ProductCreateRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _productApiClient.CreateProduct(request);
            if (result)
            {
                TempData["result"] = "Success";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Error");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> CategoryAssign(int productId)
        {
            var roleAssignRequest =  await GetRoleAssignRequest(productId); 
            return View(roleAssignRequest);
        }

        [HttpPost]
        public async Task<IActionResult> CategoryAssign( CategoryAssignRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            var result = await _productApiClient.CategoryAssign(request.Id, request);

            if (result.IsSuccessed)
            {
                TempData["result"] = "";
                return RedirectToAction("index");
            }

            ModelState.AddModelError("", result.Message);
            var assign = await GetRoleAssignRequest(request.Id);

            return View(assign);
        }




        public async Task<CategoryAssignRequest> GetRoleAssignRequest(int productId)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLangId);

            var productObj = await _productApiClient.GetById(productId, languageId);
            var categories = await _categoryApiClient.GetAll(languageId);

            var CategoriesAssignRequest = new CategoryAssignRequest();
            foreach (var role in categories)
            {
                CategoriesAssignRequest.Categories.Add(new SelectItem()
                {
                    Id = role.Id.ToString(),
                    Name = role.Name,
                    Selected = productObj.Categories.Contains(role.Name)
                });
            }

            CategoriesAssignRequest.Id = productId;

            return CategoriesAssignRequest;
        }

    }
}

eShop.AdminAplication/Views/Product/CategoryAssign.cshtml
@model eShop.ViewModels.Catalog.Products.CategoryAssignRequest
@{
    ViewData["Title"] = "Category Assign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>RoleAssign</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CategoryAssign" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @for (var i = 0; i < Model.Categories.Count; i++)
            {
                <div class="form-group">
                    <label>Set Role: @Model.Categories[i].Name</label>
                    <label asp-for="Categories[i].Name" class="control-label">
                        <input type="checkbox" asp-for="Categories[i].Selected" />
                        <input type="hidden" asp-for="Categories[i].Id" />
                        <input type="hidden" asp-for="Categories[i].Name" />
                    </label>
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                  <a class="btn btn-outline-info" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

eShop.AdminAplication/Views/Product/Create.cshtml
@model eShop.ViewModels.Catalog.Products.ProductCreateRequest

@{
    ViewData["Title"] = "Create Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
<script src="https://cdn.ckeditor.com/ckeditor5/33.0.0/classic/ckeditor.js"></script>
<script>
        ClassicEditor
    .create( document.querySelector( '#txt_Description', ), {
        // toolbar: [ 'heading', '|', 'bold', 'italic', 'link' ]
         
    } )
    .then( editor => {
        window.editor = editor;
    } )
    .catch( err => {
        console.error( err.stack );
    } );
</script>
}
<h1>Create</h1>

<h4>ProductCreateRequest</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create" asp-controller="Product" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OriginalPrice" class="control-label"></label>
                <input asp-for="OriginalPrice" class="form-control" />
                <span asp-validation-for="OriginalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea id="txt_Description" asp-for="Description" cols="10" rows="10" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <textarea asp-for="Details" class="form-control"></textarea>
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeoDescription" class="control-label"></label>
                <input asp-for="SeoDescription" class="form-control" />
                <span asp-validation-for="SeoDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeoTitle" class="control-label"></label>
                <input asp-for="SeoTitle" class="form-control" />
                <span asp-validation-for="SeoTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeoAlias" class="control-label"></label>
                <input asp-for="SeoAlias" class="form-control" />
                <span asp-validation-for="SeoAlias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThumbnailImage" class="control-label"></label>
                <input asp-for="ThumbnailImage" type="file" class="form-control" />
                <span asp-validation-for="ThumbnailImage" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

eShop.AdminAplication/Views/Product/Index.cshtml
@using eShop.ViewModels.Catalog.Common
@model PagedResult<eShop.ViewModels.Catalog.Products.ProductViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

@section ScriptAlert{
<script>
    setTimeout(function(){
     $('#msgAlert').fadeOut("slow");
    },2000);
</script>
}
<h1 class="h3 mb-2 text-gray-800">Products Manage</h1>
@if (ViewBag.SuccessMsg != null)
{
    <div id="msgAlert" class="alert alert-success" role="alert">
        @ViewBag.SuccessMsg
    </div>
}
<!-- DataTales Example -->
<div class="card shadow mb-8">
    <div class="card-header py-4">
        <div style="float:right">
            <form asp-action="Index" method="get">
                <div class="row">
                    <div class="col-md-4">
                        <input type="text" name="keyword" placeholder="Search" value="@ViewBag.keyword" class="form-control" />
                    </div>
                   
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-outline-warning">Search</button>
                @*        <button type="button" onclick="window.location.href='/User/Index'" class="btn btn-outline-dark">Reset</button>*@
                    </div>
                      <div class="col-md-5">
                       <select name="cateId" onchange="this.form.submit()" asp-items="@ViewBag.Categories" class="form-control">
                           <option value="">--Chọn danh mục--</option>
                       </select>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            Tên SP
                        </th>
                        <th>
                            Hình ảnh
                        </th>
                        <th>
                            Giá nhập
                        </th>
                        <th>
                          Số lượng tồn
                        </th>
                        <th>
                            Id
                        </th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.OriginalPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                          
                            <td>
                                @Html.DisplayFor(modelItem => item.Stock)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit","Product", new { item.Id },new { @class= "btn btn-outline-primary"}) |
                                @Html.ActionLink("Details", "Details","Product", new { item.Id },new { @class= "btn btn-outline-success"}) |
                                @Html.ActionLink("Delete", "Delete", "Product", new {id = item.Id },new { @class= "btn btn-outline-danger"}) |
                                @Html.ActionLink("Set Category", "CategoryAssign", "Product", new {productId = item.Id },new { @class= "btn btn-outline-danger"}) 
                                @* <form asp-action="Delete" method="post">
                                    @{
                                    string id = item.Id.ToString();
                                    }
                                    <input type="hidden" asp-for="@id" />
                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                    </form>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        @await Component.InvokeAsync("Pager",Model)
    </div>
</div>